In [28]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/coronavirusdataset/trend.csv
/kaggle/input/coronavirusdataset/route.csv
/kaggle/input/coronavirusdataset/case.csv
/kaggle/input/coronavirusdataset/patient.csv
/kaggle/input/coronavirusdataset/time.csv

In [29]:
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
trend = pd.read_csv('/kaggle/input/coronavirusdataset/trend.csv')
trend

          date     cold      flu  pneumonia  coronavirus
0   2019-12-07  0.12408  0.24699    0.22144      0.01309
1   2019-12-08  0.11863  0.25390    0.19617      0.00836
2   2019-12-09  0.16308  0.47880    0.33180      0.01272
3   2019-12-10  0.13981  0.40789    0.30671      0.01881
4   2019-12-11  0.13972  0.39007    0.30299      0.01854
..         ...      ...      ...        ...          ...
91  2020-03-07  0.71743  0.07690    0.22762     26.90492
92  2020-03-08  0.58752  0.06717    0.20553     26.49020
93  2020-03-09  0.45435  0.09263    0.23962     29.79228
94  2020-03-10  0.46934  0.09108    0.28635     28.49514
95  2020-03-11  0.70143  0.08945    0.30208     24.02346

[96 rows x 5 columns]

In [30]:
route = pd.read_csv('/kaggle/input/coronavirusdataset/route.csv')
route

,patient_id,date,province,city,visit,latitude,longitude
0,1,2020-01-19,Incheon,Jung-gu,airport,37.460459,126.440680
1,1,2020-01-20,Incheon,Seo-gu,hospital_isolated,37.478832,126.668558
2,2,2020-01-22,Gyeonggi-do,Gimpo-si,airport,37.562143,126.801884
3,2,2020-01-23,Seoul,Jung-gu,hospital_isolated,37.567454,127.005627
4,3,2020-01-20,Incheon,Jung-gu,airport,37.460459,126.440680
...,...,...,...,...,...,...,...
207,55,2020-02-19,Gyeongsangbuk-do,Pohang-si,hospital_isolated,36.034762,129.355059
208,56,2020-02-17,Gyeongsangbuk-do,Pohang-si,hospital,37.576420,126.972759
209,56,2020-02-13,Seoul,Dongdaemun-gu,hospital,37.593919,127.051291
210,56,2020-02-13,Seoul,Jongno-gu,hospital,37.581837,126.969186
211,56,2020-02-19,Seoul,Jungnang-gu,hospital_isolated,37.612806,127.098134

In [31]:
patient = pd.read_csv('/kaggle/input/coronavirusdataset/patient.csv')
patient

,patient_id,sex,birth_year,country,region,disease,group,infection_reason,infection_order,infected_by,contact_number,confirmed_date,released_date,deceased_date,state
0,1,female,1984.0,China,filtered at airport,NaN,NaN,visit to Wuhan,1.0,NaN,45.0,2020-01-20,2020-02-06,NaN,released
1,2,male,1964.0,Korea,filtered at airport,NaN,NaN,visit to Wuhan,1.0,NaN,75.0,2020-01-24,2020-02-05,NaN,released
2,3,male,1966.0,Korea,capital area,NaN,NaN,visit to Wuhan,1.0,NaN,16.0,2020-01-26,2020-02-12,NaN,released
3,4,male,1964.0,Korea,capital area,NaN,NaN,visit to Wuhan,1.0,NaN,95.0,2020-01-27,2020-02-09,NaN,released
4,5,male,1987.0,Korea,capital area,NaN,NaN,visit to Wuhan,1.0,NaN,31.0,2020-01-30,2020-03-02,NaN,released
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7864,7865,NaN,NaN,Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated
7865,7866,NaN,NaN,Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated
7866,7867,NaN,NaN,Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated
7867,7868,NaN,NaN,Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated
7868,7869,NaN,NaN,Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated

In [32]:
time = pd.read_csv('/kaggle/input/coronavirusdataset/time.csv')
time

,date,time,test,negative,confirmed,released,deceased,Seoul,Busan,Daegu,...,Sejong,Gyeonggi-do,Gangwon-do,Chungcheongbuk-do,Chungcheongnam-do,Jeollabuk-do,Jeollanam-do,Gyeongsangbuk-do,Gyeongsangnam-do,Jeju-do
0,2020-01-20,16,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-01-21,16,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-01-22,16,4,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-01-23,16,22,21,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-01-24,16,27,25,2,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,2020-01-25,16,27,25,2,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,2020-01-26,16,51,47,3,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
7,2020-01-27,16,61,56,4,0,0,1,0,0,...,0,2,0,0,0,0,0,0,0,0
8,2020-01-28,16,116,97,4,0,0,1,0,0,...,0,2,0,0,0,0,0,0,0,0
9,2020-01-29,16,187,155,4,0,0,1,0,0,...,0,2,0,0,0,0,0,0,0,0
10,2020-01-30,16,246,199,6,0,0,3,0,0,...,0,3,0,0,0,0,0,0,0,0
11,2020-01-31,16,312,245,11,0,0,4,0,0,...,0,5,0,0,0,1,0,0,0,0
12,2020-02-01,16,371,289,12,0,0,4,0,0,...,0,6,0,0,0,1,0,0,0,0
13,2020-02-02,16,429,327,15,0,0,5,0,0,...,0,8,0,0,0,1,0,0,0,0
14,2020-02-03,16,490,414,15,0,0,5,0,0,...,0,8,0,0,0,1,0,0,0,0
15,2020-02-04,16,607,462,16,0,0,5,0,0,...,0,8,0,0,0,1,0,0,0,0
16,2020-02-05,16,714,522,18,1,0,5,0,0,...,0,10,0,0,0,1,0,0,0,0
17,2020-02-06,16,885,693,23,2,0,10,0,0,...,0,10,0,0,0,1,0,0,0,0
18,2020-02-07,16,1352,1001,24,2,0,11,0,0,...,0,10,0,0,0,1,0,0,0,0
19,2020-02-08,16,2097,1134,24,2,0,11,0,0,...,0,10,0,0,0,1,0,0,0,0
20,2020-02-09,16,2598,1683,27,3,0,14,0,0,...,0,10,0,0,0,1,0,0,0,0
21,2020-02-10,16,3110,2552,27,4,0,14,0,0,...,0,10,0,0,0,1,0,0,0,0
22,2020-02-11,16,4325,3535,28,4,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
23,2020-02-12,16,5624,4811,28,7,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
24,2020-02-13,16,6511,5921,28,7,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
25,2020-02-14,16,7242,6679,28,7,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
26,2020-02-15,16,7734,7148,28,9,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
27,2020-02-16,16,8161,7647,29,9,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
28,2020-02-17,16,8718,7980,30,10,0,14,0,0,...,0,12,0,0,0,1,0,0,0,0
29,2020-02-18,16,9772,8923,31,12,0,14,0,1,...,0,12,0,0,0,1,0,0,0,0
30,2020-02-19,16,11173,9973,51,16,0,20,0,11,...,0,12,0,0,0,1,0,2,3,0
31,2020-02-20,16,13202,11238,104,16,1,22,8,30,...,0,12,0,0,0,1,0,25,3,0
32,2020-02-21,16,16400,13016,204,17,2,27,8,110,...,0,14,0,1,1,2,0,28,7,1
33,2020-02-22,16,21586,15116,433,18,2,30,11,193,...,1,20,6,3,1,3,1,145,7,1
34,2020-02-23,16,26179,17520,602,18,6,31,19,310,...,1,24,6,3,1,3,1,170,17,2
35,2020-02-24,16,32756,20292,833,24,8,35,34,483,...,1,35,6,3,1,3,1,193,20,2
36,2020-02-25,16,40304,25447,977,24,12,41,42,543,...,1,42,6,5,2,3,1,249,23,2
37,2020-02-26,16,53553,31576,1261,24,12,49,58,710,...,1,51,6,5,3,3,1,317,34,2
38,2020-02-27,16,66652,39318,1766,26,13,56,61,1132,...,1,62,6,8,12,5,1,345,43,2
39,2020-02-28,16,81167,48593,2337,27,13,62,65,1580,...,1,72,7,9,35,5,1,409,49,2
40,2020-02-29,16,94055,55723,3150,28,17,77,80,2236,...,1,82,7,10,55,5,3,488,59,2
41,2020-03-01,16,98921,61825,3736,30,18,87,83,2704,...,1,89,15,11,68,6,3,556,63,2
42,2020-03-02,0,109591,71580,4212,31,22,91,88,3081,...,1,92,19,11,78,6,5,624,64,2
43,2020-03-03,0,125851,85484,4812,34,28,98,90,3601,...,1,94,20,11,81,7,5,685,64,3
44,2020-03-04,0,136707,102965,5328,41,32,99,92,4007,...,1,101,21,11,82,7,4,774,65,3
45,2020-03-05,0,146541,118965,5766,88,35,103,92,4328,...,1,110,23,12,86,7,4,861,74,4
46,2020-03-06,0,164740,136624,6284,108,42,105,95,4694,...,1,120,25,15,90,7,4,984,77,4
47,2020-03-07,0,178189,151802,6767,118,44,108,96,5084,...,2,130,26,20,92,7,4,1049,82,4
48,2020-03-08,0,188518,162008,7134,130,50,120,96,5381,...,3,141,27,24,98,7,4,1082,83,4
49,2020-03-09,0,196618,171778,7382,166,51,130,96,5571,...,6,153,28,25,102,7,4,1107,83,4
50,2020-03-10,0,210144,184179,7513,247,54,141,96,5663,...,8,163,28,25,104,7,4,1117,83,4
51,2020-03-11,0,222395,196100,7755,288,60,193,98,5794,...,10,175,29,27,112,7,4,1135,84,4
52,2020-03-12,0,234998,209402,7869,333,66,212,99,5867,...,15,178,29,27,114,7,4,1143,85,4

In [33]:
route['province'].value_counts()

Seoul               85
Gyeonggi-do         56
Daegu               29
Incheon             17
Gyeongsangbuk-do     9
Gangwon-do           5
Gwangju              5
Jeollabuk-do         4
Jeollanam-do         2
Name: province, dtype: int64

Based on the value counts of the route table, in regards to provinces, Seoul South Korea has the greatest number of incidences. Could it be that more densely populated areas have a higher risk of coronavirus?

In [38]:
dates_numbering = np.empty(len(trend))
for i in range(len(trend)):
    dates_numbering[i] = i+1
date_numbers_series = pd.Series(dates_numbering)
trend['days_numbered'] = date_numbers_series

NameError: name 'date_numbers_sries' is not defined

In [39]:
sns.lineplot(x= 'days_numbered', y = 'coronavirus', data=trend)
sns.lineplot(x= 'days_numbered', y = 'cold', data=trend)
sns.lineplot(x= 'days_numbered', y = 'flu', data=trend)
sns.lineplot(x= 'days_numbered', y = 'pneumonia', data=trend)
min(trend['date']), max(trend['date'])
plt.ylabel("Incidence of Virus")
plt.title("Types of illness versus Time")

ValueError: Could not interpret input 'days_numbered'

In [ ]:
sns.lineplot(x= 'days_numbered', y = 'cold', data=trend)
sns.lineplot(x= 'days_numbered', y = 'flu', data=trend)
sns.lineplot(x= 'days_numbered', y = 'pneumonia', data=trend)
min(trend['date']), max(trend['date'])
plt.ylabel("Incidence of Virus")
plt.title("Types of illness versus Time")

During the timespan from December 7th, to March 11th, the incidence of other diseases that have vaccines and cures(cold, flu, pneumonia) have stayed relatively low and constant in terms of incidence(less than 1) in South Korea. However, between early to mid february the coronavirus, which doesn't currently have a vaccine available, has skyrocketed in incidence starting and has continued fluctuating about values of high incidence until the present. Particularly, the coronavirus has fluctuated in terms of incidence from about 40 in late january to early february to 98, and back down to 20, undulating back to 80 in late february back down again into early March.

In [ ]:
route['visit'].value_counts().plot(kind='barh', figsize=(10,10))

In [ ]:
patient['sex'].value_counts()

In [ ]:
sns.scatterplot(x= 'latitude', y = 'longitude', data=route)

In [ ]:
find_age = lambda birth_year: 2020-birth_year
patient['age'] = patient['birth_year'].apply(find_age)
average_birth_year_by_sex = patient[['sex', 'age']].groupby('sex', as_index = False).agg(np.mean)
average_birth_year_by_sex

1. Seems that the average age for both males and females in the representative sample is about 50 years old. Could it be that those who contracted the corona virus were older on average?

In [ ]:
sns.barplot(x = 'sex', y = 'age', data = patient)

In [ ]:
sns.distplot(patient['age'], kde = True, rug = True)
plt.ylabel('Percent per age')
print(max(patient['age']))
print(min(patient['age']))
two = min(patient['age'])
ninety_one = max(patient['age'])
the_range = max(patient['age']) - min(patient['age'])
print(the_range)

This distribution looks bimodal and roughly symmetric. It is slightly skewed to higher age numbers. Another question to ask, it is how long on average did it take people to get released from the hospital and presumably cured for the coronavirus?

In [ ]:
patients_released = patient[patient['state'] == 'released']
patients_confimed_date = patient['confirmed_date'].str.split("-", expand = True)
patients_confimed_date = patients_confimed_date.rename(columns = {0: 'Year', 1: 'Month', 2: 'Day'}).fillna(0)
patients_released_date = patient['released_date'].str.split("-", expand = True)
patients_released_date = patients_released_date.rename(columns = {0: 'Year', 1: 'Month', 2: 'Day'}).fillna(0)
patients_confimed_date['Days'] = patients_confimed_date['Month'].astype(int)*30+patients_confimed_date['Day'].astype(int)
patients_released_date['Days'] = patients_released_date['Month'].astype(int)*30+patients_released_date['Day'].astype(int)
patient['Duration'] = patients_released_date['Days'] - patients_confimed_date['Days'] 
patient = patient[patient['Duration'] > 0]
patient['Duration']

In [ ]:
sns.distplot(patient['Duration'], kde = True, rug = True)
plt.ylabel('Percent per Duration')
plt.title('Distribution of Cornonavirus Durations of (Potential) Recovery')
average_duration = np.mean(patient['Duration'])
print(average_duration)

Most patients got cured in about a span of 12 days. We can cautiously make the claim that most of these patients contracted the virus and were cured within on average a 12 day timespan. However, others that may not have had the coronavirus were forcefully detained for public health reasons. This histogram appears unimodal, and skewed to higher durations(indicative of those potentially in serious condition and requring further recovery). Let us now explore the association between duration and age.

In [ ]:
sns.scatterplot(x = patient['age'], y = patient['Duration'], hue = patient['sex'])

There appears to be no association between age and duration of stay in the hospital. In short, based on this analysis, Coronavirus targets all ages and both genders equally, and the duration most likely is associated with the severity of the conditions, represented by the skew to right of the hospital durations.